//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodimac.SCPRO.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Table {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Table() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sodimac.SCPRO.Common.Resource.Table", typeof(Table).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal.
        /// </summary>
        public static string Canal {
            get {
                return ResourceManager.GetString("Canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinscripcion.
        /// </summary>
        public static string Desinscripcion {
            get {
                return ResourceManager.GetString("Desinscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesinscripcionEvidencia.
        /// </summary>
        public static string DesinscripcionEvidencia {
            get {
                return ResourceManager.GetString("DesinscripcionEvidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstadoSolicitud.
        /// </summary>
        public static string EstadoSolicitud {
            get {
                return ResourceManager.GetString("EstadoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NivelEducativo.
        /// </summary>
        public static string NivelEducativo {
            get {
                return ResourceManager.GetString("NivelEducativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficio.
        /// </summary>
        public static string Oficio {
            get {
                return ResourceManager.GetString("Oficio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RazonDesinscripcion.
        /// </summary>
        public static string RazonDesinscripcion {
            get {
                return ResourceManager.GetString("RazonDesinscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        public static string Solicitud {
            get {
                return ResourceManager.GetString("Solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        public static string Tienda {
            get {
                return ResourceManager.GetString("Tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoDocumentoIdentidad.
        /// </summary>
        public static string TipoDocumentoIdentidad {
            get {
                return ResourceManager.GetString("TipoDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubigeo.
        /// </summary>
        public static string Ubigeo {
            get {
                return ResourceManager.GetString("Ubigeo", resourceCulture);
            }
        }
    }
}
